services:
  auth:
    image: quay.io/keycloak/keycloak
    ports:
      - "8180:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command:
      - start-dev
      - --import-realm
    volumes:
      - ./keycloak/realm.json:/opt/keycloak/data/import/realm.json
  mongo-db:
    image: mongo
    container_name: chatapp-mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./db/:/data/chatapp-mongodb